name: Build for windows

on: workflow_dispatch

jobs:
  build-windows:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        conda install cython
        pip install pygame, py2ese
    - name: update SWIG
      run: sudo apt -y install swig
    - name: Try to compile extentions
      run: |
        python make.py build
    - name: build for windows
      run: python build_win.py
    - name: list
      run: ls
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        path: build.exe
        name: Build
