name: Python Package using Conda

on:
  push:
    branches:
    - master

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Try to compile extentions
      run: |
        python make.py build
    - name: list
      run: ls ./mask_extension
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
         name: built
         path: ./mask_extension/_mask.pyd
    - name: Test
      run: |
        python
        import mask_extension._mask
